smrtcells_targets:
  - alignment
  - stats
  - coverage  # req: alignment
  - coverage_qc  # req: alignment
  - kmers

sample_targets:
  - pbsv_vcf  # req: alignment in config['smrtcells_targets']
  - deepvariant  # req: alignment in config['smrtcells_targets']
  - whatshap  # req: deepvariant
  - coverage  # req: whatshap
  - kmers  # req: kmers in config['smrtcells_targets']
  - assembly
  - tandem-genotypes  # req: whatshap
  - trgt  # req: whatshap
  - 5mc_cpg_pileup # req: whatshap; also requires uBAM input with basemods

cohort_targets:
  - pbsv_vcf  # req: pbsv_vcf in config['sample_targets']
  - svpack  # req: pbsv_vcf in config['sample_targets']
  - deepvariant_vcf  # req: deepvariant, whatshap in config['sample_targets']
  - slivar  # req: deepvariant, whatshap in config['sample_targets']
  - trio_assembly

# jellyfish and genomescope
kmer_length: 21

# pbsv
# pass along extra parameters to pbsv that will override the hifi defaults
pbsv_call_extra: ""

# deepvariant 
N_SHARDS: 256
# deepvariant call_variants can be run as GPU or CPU-only
# additional configuration specific to job schedulers can be found variables.env
# change to True if you don't have GPUs available
cpu_only: True
deepvariant_cpu_version: '1.5.0'
deepvariant_gpu_version: '1.5.0-gpu'

# glnexus
GLNEXUS_VERSION: 'v1.4.1'

# last/tandem-genotypes
score_matrix: 'resources/tandem-genotypes/score_matrix.par'

# slivar
slivar_js: 'resources/slivar/slivar-functions.js'
# slivar filters
# gnomad -> frequency in gnomAD v3
# hprc -> frequency in 40 HPRC samples sequenced with HiFi
# af -> allele frequency
# nhomalt -> number of samples with homalt genotype
# gq -> genotype quality as output by DeepVariant or GLnexus
max_gnomad_af: 0.01  # for all variants
max_hprc_af: 0.01  # for all variants
max_gnomad_nhomalt: 4  # for all variants
max_hprc_nhomalt: 4  # for all variants
max_gnomad_ac: 4  # for 'dominant' variants
max_hprc_ac: 4  # for 'dominant' variants
min_gq: 5

# lookups for slivar tsv annotations
lof_lookup: 'resources/slivar/lof_lookup.txt'
clinvar_lookup: 'resources/slivar/clinvar_gene_desc.txt'

# cohorts yaml
cohort_yaml: 'cohort.yaml'

# lookups for gene mapping
ensembl_to_hgnc: 'resources/hpo/ensembl.hgncSymbol.tsv'

# lookups for HPO annotations
hpo:
  terms: 'resources/hpo/hpoTerms.txt'
  dag: 'resources/hpo/hpoDag.txt'
  annotations: 'resources/hpo/ensembl.hpoPhenotype.tsv'
